services:
  cpp:
    build:
      context: .
    volumes:
      - ./src/:/root/cpp/src/
      - ./sample.sh:/root/cpp/sample.sh
      - ./run_test.sh:/root/cpp/run_test.sh
      - ./.vscode/:/root/.vscode/
      - ./templates/cpp/:/root/.config/atcoder-cli-nodejs/cpp
    stdin_open: true
    tty: true
